"use client";
import { useEffect, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type KPI = { revenue:number; occupancy:number; adr:number; revpar:number; cancellation_rate:number };
type Point = { date:string; revenue:number; occupancy:number; adr:number; revpar:number };
type Recommendation = { property:string; current_adr:number; recommended_rate:number; adjustment_percent:number; reasons:string[] };

export default function Home() {
  const [kpis,setKpis]=useState<KPI>(); const [trend,setTrend]=useState<Point[]>([]); const [pricing,setPricing]=useState<Recommendation[]>([]); const [properties,setProperties]=useState<any[]>([]); const [error,setError]=useState("");
  useEffect(()=>{Promise.all([fetch(`${API}/api/overview`).then(r=>r.json()),fetch(`${API}/api/pricing`).then(r=>r.json()),fetch(`${API}/api/properties`).then(r=>r.json())]).then(([o,p,props])=>{setKpis(o.kpis);setTrend(o.trend);setPricing(p);setProperties(props)}).catch(()=>setError("Revenue API is unavailable."))},[]);
  const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
  return <main><nav><div className="brand"><i>NS</i><span>Northstar<small>Revenue Intelligence</small></span></div><div className="period">Portfolio overview · July 2026</div></nav><header><div><p className="eyebrow">EXECUTIVE REVENUE DESK</p><h1>See demand.<br/><em>Shape revenue.</em></h1></div><p>One decision layer for occupancy, pricing, channel mix, and forward demand across your hotel portfolio.</p></header>{error&&<div className="error">{error}</div>}<section className="kpis">{kpis&&[["Total Revenue",money(kpis.revenue),"Portfolio room revenue"],["Occupancy",`${kpis.occupancy}%`,"Rooms sold / available"],["ADR",money(kpis.adr),"Average daily rate"],["RevPAR",money(kpis.revpar),"Revenue per available room"]].map(([label,value,note])=><article key={label}><small>{label}</small><strong>{value}</strong><span>{note}</span></article>)}</section><section className="grid"><article className="panel chart"><div className="title"><div><small>PERFORMANCE</small><h2>Revenue trend</h2></div><span>Daily</span></div><ResponsiveContainer width="100%" height={270}><AreaChart data={trend}><defs><linearGradient id="revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#c66a3a" stopOpacity={.35}/><stop offset="95%" stopColor="#c66a3a" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>v.slice(5)} /><YAxis/><Tooltip formatter={(v)=>money(Number(v))}/><Area type="monotone" dataKey="revenue" stroke="#c66a3a" strokeWidth={3} fill="url(#revenue)"/></AreaChart></ResponsiveContainer></article><article className="panel"><div className="title"><div><small>RATE DESK</small><h2>Pricing moves</h2></div></div>{pricing.map(item=><div className="rate" key={item.property}><div><strong>{item.property}</strong><small>{item.reasons.join(" · ")}</small></div><div><b>{money(item.recommended_rate)}</b><span className={item.adjustment_percent>=0?"up":"down"}>{item.adjustment_percent>=0?"+":""}{item.adjustment_percent}%</span></div></div>)}</article><article className="panel properties"><div className="title"><div><small>PORTFOLIO</small><h2>Property comparison</h2></div></div>{properties.map(item=><div className="property" key={item.property}><strong>{item.property}</strong><span>{item.occupancy}% occ.</span><b>{money(item.revpar)} RevPAR</b></div>)}</article><article className="panel insight"><small>REVENUE SIGNAL</small><h2>Demand is strengthening</h2><p>Booking pace and event demand support selective rate increases while protecting direct-channel conversion.</p><button>Review recommendations →</button></article></section></main>;
}
